### ISSUE TITLE
Spectacle

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dev-setup#18]
To easily re-size windows on Mac using keyboard shortcuts, download and use Spectacle:
https://www.spectacleapp.com

it's open source: https://github.com/eczarny/spectacle and the developer is legit.

# Todo

+ [ ] Create a Pull Request adding Spectacle to the list of recommended apps for Mac users.

**Comment by miguelmartins17** [comment]
I already Installed Spectable 👋.

**Comment by nelsonic** [comment]
@miguelmartins17 that's _great_! 🎉
Now please create a Pull Request to add the instructions to the **README.md** file so that the _next_ person knows what to do.
Thanks. 👍

**Comment by miguelmartins17** [comment]
I am working on the spectacle installation guide and what the advantages and disadvantages are.
And in which are the shortcuts of the spectacle.

**Comment by iteles** [comment]
This was completed in https://github.com/dwyl/dev-setup/pull/29
