### ISSUE TITLE
Please Give Feedback!

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dev-setup#26]
@miguelmartins17 please read and follow this guid and give us feedback! 💡 
If you have questions, please open issues! ❓ 
Thanks! ☀️

**Comment by miguelmartins17** [comment]
@nelsonic Yes Im gonna do this today !

**Comment by miguelmartins17** [comment]
Installing Atom right now ! 👍

**Comment by miguelmartins17** [comment]
@nelsonic While Running Atom it appears an option saying "Version Control with Git and Github".
How can I Open Text I want from Github ?? 🤔

**Comment by nelsonic** [comment]
@miguelmartins17 great that you are following this guide. 🥇 
please see https://github.com/dwyl/dev-setup/issues/18 (install spectacle)  👓 
and create a Pull Request to add it to the `README.md` ➕ 
Thanks! 🌻

**Comment by nelsonic** [comment]
@miguelmartins17 how did you get on with following this guide today? Did you open any issues with questions? 💭

**Comment by miguelmartins17** [comment]
@nelsonic Im working now in the "Learn how to use Git+Github" its the only thing missing in my feedback.
Working too in getting my app on the play store.

**Comment by nelsonic** [comment]
Look forward for seeing your App on the Google Play Store: https://github.com/miguelmartins17/Englisher-and-Englisher-Game/issues/1 👍

**Comment by miguelmartins17** [comment]
@nelsonic I'm having some trouble putting the app in the play store.
The API number of my app is giving me some problems and I'm not being able to solve it.
I tried to change the number to 28 and now I have another mistake.




![LOkvmSPVSs](https://user-images.githubusercontent.com/27420533/71988005-170c0b00-3227-11ea-82d5-9405b37172e7.png)

**Comment by iteles** [comment]
@miguelmartins17 That's the perfect comment to add to https://github.com/miguelmartins17/Englisher-and-Englisher-Game/issues/1 (and don't forget to add in comments on your steps as you're doing them) 😊

**Comment by iteles** [comment]
We didn't quite get 'feedback' but there were a couple of PRs to improve the content https://github.com/dwyl/dev-setup/pull/29 https://github.com/dwyl/dev-setup/pull/30 👍 
I'd like to close this issue as it's become a little 'noisy' and we can re-open if needed. 

@nelsonic Shall we add a note to L37 to tell people that this repo is a great place to start before we close this issue or are we happy that it's implied that we welcome feedback on everything?
![image](https://user-images.githubusercontent.com/4185328/79358539-3a86d600-7f39-11ea-89b2-056bca597ecd.png)

**Comment by nelsonic** [comment]
@iteles yeah, OK to close. 👍
