### ISSUE TITLE
Software is all Optional

### ISSUE THREAD

**Issue by nelsonic** [dwyl/dev-setup#3]
From: https://github.com/dwyl/start-here/blob/8bbd28d2ab0c3b5a2a266a1e41fd160fc6ee3038/README.md#software

_Installing_ software is 100% optional. You can use Cloud9 to develop completely online: https://c9.io/

If you prefer to develop offline or have a faster response, you will need:
- [x] A text editor. e.g. [Atom](https://atom.io/)
- [x] [Node.js](http://nodejs.org/download/) for building server-side apps.

**Comment by iteles** [comment]
:+1:

**Comment by nelsonic** [comment]
on re-reading the paragraph that was added, it's confusing. 🤔 
why would I need a "dev setup" if the software is optional? 🤷‍♂️
