### ISSUE TITLE
Icloud's Storage Full 

### ISSUE THREAD

**Issue by miguelmartins17** [dwyl/dev-setup#32]
I created an account at Apple when I started working with this computer but now it tells me that I have the Icloud Storage full.

**Comment by miguelmartins17** [comment]
This is what comes to me when I open Finder.

![Screen Shot 2020-02-10 at 18 11 48](https://user-images.githubusercontent.com/27420533/74177088-f1f92680-4c30-11ea-9917-e3890a8b96c6.png)

**Comment by nelsonic** [comment]
@miguelmartins17 seems like you are automatically uploading large documents/files to iCloud without know it. And I think I know what it is ... from reading your recent PR: https://github.com/dwyl/learn-flutter/pull/29/files#r377235703 you are storing your `flutter` in `/Users/m/Documents` which means that the Mac is automatically uploading them to iCloud and taking up space! 
If you move `flutter` to `/Users/m/development` (_as suggested in the official Flutter docs_) it will no longer be uploaded to iCloud and the warning will disappear. 
Let us know how you get on. 👍

**Comment by miguelmartins17** [comment]
I passed the Flutter folder to development.

![Screen Shot 2020-02-10 at 18 38 44](https://user-images.githubusercontent.com/27420533/74179288-07704f80-4c35-11ea-98bb-03c9003d64da.png)

It no longer appears to me that Icloud's Storage is full.



![Screen Shot 2020-02-10 at 18 40 31](https://user-images.githubusercontent.com/27420533/74179308-0dfec700-4c35-11ea-9d8f-05da883cda9d.png)

**Thank you very much.**

**Comment by nelsonic** [comment]
@miguelmartins17 should I get a job working as "Tech Support" for Apple at Fnac? 😜

**Comment by miguelmartins17** [comment]
@nelsonic Sure! 😄

**Comment by miguelmartins17** [comment]
@iteles Sorry Ines I didn't understand something, what should I test ?

**Comment by nelsonic** [comment]
@miguelmartins17 Inês just means that you should _confirm_ that this issue is resolved
and _close_ the issue if it's no longer a problem. 👍 

**`please-test`** label is applied so the person who originally opened the issue can "test" it 
and if it's "fixed", close the issue. see: https://github.com/dwyl/labels#labels

**Comment by miguelmartins17** [comment]
Now I understand, yes, it is `solved `now that the Icloud Storage is full. Thanks a lot for your help 😄

**Comment by iteles** [comment]
@miguelmartins17 You may also have seen this in our contributing guidelines: https://github.com/dwyl/contributing#step-4-reviewers-review-comment-on-and-merge-the-pull-request
